kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  annotations:
    description: our first testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Subhash; sleep 5; done"]

